In [62]:
from data_setup import *
import polars as pl

In [64]:
dl = pl.read_database_uri('select * from pd023',connMy)
dl

shape: (58, 2)
┌──────┬──────────────────────────┐
│ 月份 ┆ 高手                     │
│ ---  ┆ ---                      │
│ i64  ┆ str                      │
╞══════╪══════════════════════════╡
│ 1    ┆ 阳顶天                   │
│ 1    ┆ 狄云                     │
│ 1    ┆ 虚竹, 杨过               │
│ 1    ┆ 独孤求败, 风清扬         │
│ 1    ┆ 段誉                     │
│ 1    ┆ 小龙女                   │
│ 1    ┆ 慕容博                   │
│ 1    ┆ 瑛姑，黄蓉               │
│ 2    ┆ 风清扬                   │
│ 2    ┆ 袁承志                   │
│ 2    ┆ 梅超风；黄蓉             │
│ 2    ┆ 萧远山, 石破天，乔峰     │
│ 2    ┆ 林朝英, 张无忌           │
│ 2    ┆ 张三丰, 阳顶天           │
│ 2    ┆ 袁承志                   │
│ …    ┆ …                        │
│ 8    ┆ 林朝英                   │
│ 8    ┆ 天山童姥, 段誉           │
│ 8    ┆ 石破天                   │
│ 8    ┆ 风清扬,令狐冲            │
│ 8    ┆ 阳顶天, 火云邪神         │
│ 9    ┆ 袁承志                   │
│ 9    ┆ 瑛姑, 瑛姑               │
│ 9    ┆ 杨过                     │
│ 9    ┆ 段誉                     │
│ 9    ┆ 令狐冲                   │
│ 9    ┆ 火云邪神                 │
│ 10   ┆ 慕容博, 萧远山, 天山童姥 │
│ 10   ┆ 石破天                   │
│ 10   ┆ 风清扬，令狐冲           │
│ 10   ┆ 张三丰, 张无忌\ 紫衫龙王 │
└──────┴──────────────────────────┘

In [96]:
dl.group_by(
    pl.first(),maintain_order=True
).agg(pl.last().str.join(",")).select(
    pl.first(),
    pl.concat_str(
        pl.last(),pl.last().shift(-1),pl.last().shift(-2),separator=","
    )
).drop_nulls().with_columns(
    pl.last().str.extract_all(r'[\u4e00-\u9fff]+').list.eval(
        pl.element().value_counts(sort=True)
    )
).explode(pl.last()).unnest(pl.last()).filter(
    pl.last() == pl.last().max().over(pl.first())
).group_by(pl.nth(1),maintain_order=True).agg(
    pl.len().alias("count")
).sort(pl.col("count"),descending=True).head(3)

shape: (3, 2)
┌──────────┬───────┐
│          ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ 张三丰   ┆ 3     │
│ 段誉     ┆ 3     │
│ 火云邪神 ┆ 3     │
└──────────┴───────┘

In [104]:
(
    dl.group_by(pl.first(), maintain_order=True)
    .agg(pl.last().str.join(","))
    .with_columns(
        pl.concat_str(pl.last(), pl.last().shift(-1), pl.last().shift(-2), separator=",")
        .str.extract_all(r'[\u4e00-\u9fff]+')
        .list.eval(
        pl.element().value_counts(sort=True)
    )
    ))

shape: (10, 2)
┌──────┬────────────────────────────────────────────────┐
│ 月份 ┆ 高手                                           │
│ ---  ┆ ---                                            │
│ i64  ┆ list[struct[2]]                                │
╞══════╪════════════════════════════════════════════════╡
│ 1    ┆ [{"风清扬",3}, {"黄蓉",3}, … {"扫地僧",1}]     │
│ 2    ┆ [{"乔峰",3}, {"张三丰",3}, … {"虚竹",1}]       │
│ 3    ┆ [{"郭靖",3}, {"扫地僧",3}, … {"张无忌",1}]     │
│ 4    ┆ [{"阳顶天",3}, {"张三丰",3}, … {"紫衫龙王",1}] │
│ 5    ┆ [{"袁承志",2}, {"瑛姑",2}, … {"灭绝师太",1}]   │
│ 6    ┆ [{"段誉",3}, {"石破天",3}, … {"令狐冲",1}]     │
│ 7    ┆ [{"段誉",3}, {"火云邪神",3}, … {"杨过",1}]     │
│ 8    ┆ [{"令狐冲",3}, {"袁承志",2}, … {"紫衫龙王",1}] │
│ 9    ┆ null                                           │
│ 10   ┆ null                                           │
└──────┴────────────────────────────────────────────────┘

In [ ]:
(
    dl
    .group_by(pl.first(), maintain_order=True)
    .agg(pl.last())
    .with_columns(
        pl.concat_list(
            [pl.last().shift(-i) for i in range(3)]
        )
    ).drop_nulls(pl.last()).with_columns(
        pl.last().list.eval(
            pl.element().str.extract_all(r'[\u4e00-\u9fff]+')
        )
    ).explode(pl.last()).explode(pl.last())
)

shape: (250, 2)
┌──────┬──────────┐
│ 月份 ┆ 高手     │
│ ---  ┆ ---      │
│ i64  ┆ str      │
╞══════╪══════════╡
│ 1    ┆ 阳顶天   │
│ 1    ┆ 狄云     │
│ 1    ┆ 虚竹     │
│ 1    ┆ 杨过     │
│ 1    ┆ 独孤求败 │
│ 1    ┆ 风清扬   │
│ 1    ┆ 段誉     │
│ 1    ┆ 小龙女   │
│ 1    ┆ 慕容博   │
│ 1    ┆ 瑛姑     │
│ 1    ┆ 黄蓉     │
│ 1    ┆ 风清扬   │
│ 1    ┆ 袁承志   │
│ 1    ┆ 梅超风   │
│ 1    ┆ 黄蓉     │
│ …    ┆ …        │
│ 8    ┆ 瑛姑     │
│ 8    ┆ 瑛姑     │
│ 8    ┆ 杨过     │
│ 8    ┆ 段誉     │
│ 8    ┆ 令狐冲   │
│ 8    ┆ 火云邪神 │
│ 8    ┆ 慕容博   │
│ 8    ┆ 萧远山   │
│ 8    ┆ 天山童姥 │
│ 8    ┆ 石破天   │
│ 8    ┆ 风清扬   │
│ 8    ┆ 令狐冲   │
│ 8    ┆ 张三丰   │
│ 8    ┆ 张无忌   │
│ 8    ┆ 紫衫龙王 │
└──────┴──────────┘

In [107]:
expr = pl.col("abc")

expr.meta.output_name()

'abc'

In [103]:
pl.concat_str(
    [pl.col("combined").shift(-i) for i in range(3)],
    separator=","
).alias("window")